version: '3.8'

services:
  prediction-service:
    build: ./prediction-service
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  visualization-service:
    build: ./visualization-service
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 